name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying code in server
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd tiktok-live-ui
            git pull origin master
            yarn install
            yarn build
            rm -rf /var/www/html/tiktok-live-ui
            cp -r dist /var/www/html/tiktok-live-ui