name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying code in server
        uses: appleboy/ssh-action@v1.0.0
        with:
          command_timeout: 5m
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd tiktok-live-ui
            git pull origin master
            yarn install
            cp ${{ secrets.ENV_FOLDER }}/tiktok-live-ui .env
            rm -rf ${{ secrets.DEPLOY_FOLDER }}/tiktok-live-ui
            yarn build
            cp -r dist ${{ secrets.DEPLOY_FOLDER }}/tiktok-live-ui
